# CodeRabbit Configuration
# This file configures how CodeRabbit reviews your code

# Global settings
global:
  # Review frequency
  review_frequency: "every_pr"
  
  # Languages to focus on
  languages:
    - python
    - typescript
    - javascript
    - sql
    - yaml
    - json

# Path-specific settings
paths:
  # Backend Python code
  "backend/**/*.py":
    focus:
      - code_quality
      - security
      - performance
      - best_practices
    ignore:
      - "**/__pycache__/**"
      - "**/migrations/**"
      - "**/venv/**"

  # Frontend TypeScript/JavaScript
  "frontend/**/*.{ts,tsx,js,jsx}":
    focus:
      - code_quality
      - performance
      - accessibility
      - best_practices
    ignore:
      - "**/node_modules/**"
      - "**/dist/**"
      - "**/build/**"

  # Database files
  "backend/database/**/*.py":
    focus:
      - security
      - data_integrity
      - performance
      - migrations

  # API endpoints
  "backend/api/**/*.py":
    focus:
      - security
      - error_handling
      - input_validation
      - documentation

# Review settings
review:
  # Minimum confidence level for suggestions
  min_confidence: 0.7
  
  # Maximum number of comments per PR
  max_comments: 20
  
  # Include suggestions for:
  suggestions:
    - code_improvements
    - security_issues
    - performance_optimizations
    - best_practices
    - documentation
    - test_coverage

# Ignore patterns
ignore:
  - "**/*.log"
  - "**/package-lock.json"
  - "**/pnpm-lock.yaml"
  - "**/requirements.txt"
  - "**/.env*"
  - "**/node_modules/**"
  - "**/venv/**"
  - "**/__pycache__/**"