# CodeRabbit Configuration
# This file configures how CodeRabbit reviews your code

# Global settings
global:
  review_frequency: "every_pr"
  languages:
    - python
    - typescript
    - javascript
    - sql
    - yaml
    - json

# Path-specific settings
paths:
  "backend/**/*.py":
    focus:
      - code_quality
      - security
      - performance
      - best_practices
    ignore:
      - "**/__pycache__/**"
      - "**/migrations/**"
      - "**/venv/**"

  "frontend/**/*.{ts,tsx,js,jsx}":
    focus:
      - code_quality
      - performance
      - accessibility
      - best_practices
    ignore:
      - "**/node_modules/**"
      - "**/dist/**"
      - "**/build/**"

  "backend/database/**/*.py":
    focus:
      - security
      - data_integrity
      - performance
      - migrations

  "backend/api/**/*.py":
    focus:
      - security
      - error_handling
      - input_validation
      - documentation

# Review settings
review:
  min_confidence: 0.7
  max_comments: 20
  suggestions:
    - code_improvements
    - security_issues
    - performance_optimizations
    - best_practices
    - documentation
    - test_coverage

  # Auto-review only PRs targeting these branches
  auto_review:
    enabled: true
    targets:
      branches:
        - main
        - develop-v1

# Ignore patterns
ignore:
  - "**/*.log"
  - "**/package-lock.json"
  - "**/pnpm-lock.yaml"
  - "**/requirements.txt"
  - "**/.env*"
  - "**/node_modules/**"
  - "**/venv/**"
  - "**/__pycache__/**"
