[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build completed successfully'"
]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
