[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build completed successfully'"
]

[start]
cmd = "python deploy_railway.py && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
