name: CodeRabbit Review
on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  review:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Run CodeRabbit
        uses: coderabbitai/coderabbit-action@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Add configuration file path if you want to customize behavior
          # config: .coderabbit.yaml
